# Generated by Django 3.2.3 on 2021-06-01 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0008_alter_postimages_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimages',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
